# Generated by Django 4.0.5 on 2022-06-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('img', models.TextField()),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
